name: Hello World
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
 

jobs:
  workflow:

    runs-on: ubuntu-latest

    steps:
        - name: Installing OS Dependencies
          run: echo "Hello, World"

        - name: Install npm
          run: npm install
