name: CI Workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
    issues:
        types: [opened, reopened, closed]
 

jobs:
  workflow:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install OS dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential

        - name: Install npm
          run: npm install

        - name: Build npm
          run: npm run build

        - name: Run all tests
          run: npm run test

        - name: New issue found
          run: |
            echo "Here's an issue that just came up!"
            echo "Issue title: ${{ github.event.issue.title }}"

